### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by leifdenby** [mllam/mllam-data-prep#5]
This issue represents the evolving roadmap of the `mllam-data-prep` package and is updated monthly based on the mllam developer meetings (4th week of the month).

*v0.6.0*
- [ ] add ability to create top-of-atmopshere radiation field from inputs - https://github.com/mllam/mllam-data-prep/pull/34

*v0.5.0*
- [x] Fix for typo in example (unecessary f"" in format string) - https://github.com/mllam/mllam-data-prep/pull/35
- [x] Replace global config for dataclasses_wizard with specific config - https://github.com/mllam/mllam-data-prep/pull/36
- [x] Add "extra" section which is ignored by mllam-data-prep (used for projection info in neural-lam datastores) **or** add support for projections in mllam-data-prep, https://github.com/mllam/mllam-data-prep/pull/30

*v0.4.0*
- [x] add optional output path argument to parser. #26
- [x] fix bug by making dependency distributed optional #27
- [x] change config example to call validation split val instead of validation https://github.com/mllam/mllam-data-prep/pull/28
- [x] fix typo in install dependency distributed #20
- [x] add missing psutil requirement. https://github.com/mllam/mllam-data-prep/pull/21.

*v0.3.0*
- [x] add command line flags for running through dask-distributed on the local machine

*v0.2.0*
- [x] replace existing config-yaml files with python [dataclasses](https://docs.python.org/3/library/dataclasses.html) that are [serialised to yaml](https://github.com/rnag/dataclass-wizard) for storing the config #8 
- [x] add splitting and calculation of statistics https://github.com/mllam/mllam-data-prep/pull/10
- [x] add inclusion of source variable `units` and `long_name` as additional coordinates as `{output_feature}_units` `{output_feature}_long_name` https://github.com/mllam/mllam-data-prep/pull/11

*v0.1.0*

<hr />

*not currently on roadmap*
- add support for projecting/interpolating between different grids

**Comment by joeloskarsson** [comment]
In the developer calls it had been decided to switch from these roadmap issues to using the github milestones. Please see https://github.com/mllam/mllam-data-prep/milestones for the up to date roadmap.
